// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkcbkzsnwnobemjxomwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrY2JrenNud25vYmVtanhvbXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDAwOTgsImV4cCI6MjA2NjU3NjA5OH0.bB6a8eg9ZUAsE-0TUDK2zuiUyAAhyzXS_5bYEBZVGRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);